[package]
name = "sr-blog-gen"
version = "0.1.0"
authors = ["Shareef Raheem <r.shareef28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
